server:
  error:
    include-stacktrace: never
spring:
  jpa:
    open-in-view: true
    show-sql: true
kakao:
  search-place-by-keyword-url: https://dapi.kakao.com/v2/local/search/keyword.json
  rest-api-key: 58eef2e2c12deb84bb4f0911a29f5b61
